services:
  - type: web
    name: Rideer_Application_Api
    runtime: java
    buildCommand: "mvn clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
